language: csharp
solution: AwesomeSockets.sln
mono:
  - latest
  - 4.2.1
  - 3.12.0
  - 3.8.0
  - 3.2.8
install:
  - wget -P .paket/ "https://github.com/fsprojects/Paket/releases/download/3.19.4/paket.bootstrapper.exe"
  - wget -P .paket/ "https://github.com/fsprojects/Paket/releases/download/3.19.4/paket.targets"
  - mono .paket/paket.bootstrapper.exe
  - mono .paket/paket.exe install
script: 
  - xbuild /p:Configuration=Release AwesomeSockets.sln
  - mono packages/NUnit.ConsoleRunner/tools/nunit3-console.exe AwesomeSockets.Tests/bin/Release/AwesomeSockets.Tests.dll

