version: '2.0.{build}.0'
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
configuration: Release
platform: Any CPU
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
build:
  publish_nuget: true
  publish_nuget_symbols: false
init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
before_build:
- appveyor-retry dotnet restore -v Minimal
- '$path = "C:\projects\awesomesockets\src\AwesomeSockets\project.json"; $version = {version}; (Get-Content $path) -replace ''"version":\s+"(\d+\.\d+\.\d+\.\d+(-\*)?)"'',"`"version`": `"$version`"" | out-file $path'
build_script:
- dotnet build "src\AwesomeSockets" -c %CONFIGURATION%
after_build:
- dotnet pack "src\AwesomeSockets" -c %CONFIGURATION% --no-build -o artifacts
test_script:
- dotnet test "test\AwesomeSockets.Tests" -c %CONFIGURATION%
- dotnet test "test\AwesomeSockets.Acceptance.Tests" -c %CONFIGURATION%
artifacts:
- path: artifacts\**\*.*
deploy:
  provider: NuGet
  api_key:
    secure: YYJVXyOvCQ0+eH0+nYybXRh3lxCdCXBcMMduj+YzdPmJWASjKMlkdu72BvW4Xksu
  skip_symbols: true
